@startuml

class Juego
class Mundo
class Nivel
class Personaje
class Mario
class Luigi
class Enemigo
class Goomba
class KoopaTroopa
class Bowser
class JefeFinal
class Hongo
class FlorDeFuego
class Estrella
class Moneda
class Bloque
class BloquePregunta
class BloqueLadrillo
class Tuberia
class Plataforma
class PlataformaMovil
class Vida
class Puntaje
class ProyectilFuego
class Caparazon

Mario --|> Personaje
Luigi --|> Personaje
Enemigo --|> Personaje
Goomba --|> Enemigo
KoopaTroopa --|> Enemigo
JefeFinal --|> Enemigo
Bowser --|> JefeFinal
PlataformaMovil --|> Plataforma
BloquePregunta --|> Bloque
BloqueLadrillo --|> Bloque

Juego *-- Mundo
Mundo *-- Nivel
Nivel *-- Enemigo
Nivel *-- Bloque
Nivel *-- Plataforma
Nivel *-- Tuberia
Nivel *-- Moneda
Mario *-- Vida
Mario *-- Puntaje
Mario *-- ProyectilFuego
KoopaTroopa *-- Caparazon

Mario o-- Hongo
Mario o-- FlorDeFuego
Mario o-- Estrella
Mario o-- Moneda
BloquePregunta o-- Hongo
BloquePregunta o-- FlorDeFuego
BloquePregunta o-- Moneda

@enduml
