@startuml

class Juego
class Mundo
class Nivel

class Personaje{
+corazon corazones[3]
}

class Mario{
+ entrarTuberia()
+ salirTuberia()
}

class Luigi{
+ entrarTuberia()
+ salirTuberia()
}

class Enemigo
class Goomba{
+ acercar()
- morir()
}

class KoopaTroopa{
+ acercar()
- morir()
}

class Bowser{
+ acercar()
+ lanzarBolaFuego()
- morir()
}

class JefeFinal
class PrincesaPeach

class Hongo
class FlorDeFuego
class Estrella
class Moneda

class Bloque
class BloquePregunta
class BloqueLadrillo

class Tuberia{
-nivelEntrada : Nivel
-nivelSalida : Nivel
+ transportar(personaje)
}

class Plataforma
class Bandera
class Castillo

class Vida
class Puntaje
class ProyectilFuego
class Caparazon
class Crecimiento


Mario --|> Personaje
Luigi --|> Personaje

Enemigo --|> Personaje
Goomba --|> Enemigo
KoopaTroopa --|> Enemigo
JefeFinal --|> Enemigo
Bowser --|> JefeFinal

BloquePregunta --|> Bloque
BloqueLadrillo --|> Bloque


Juego "1" *-- "1..*" Mundo
Mundo "1" *-- "1..*" Nivel

Nivel "1" *-- "1..*" Enemigo
Nivel "1" *-- "1..*" Bloque
Nivel "1" *-- "1..*" Plataforma
Nivel "1" *-- "0..*" Tuberia
Nivel "1" *-- "0..*" Moneda
Nivel "1" *-- "1" Bandera
Nivel "1" *-- "0..1" Castillo

Mario "1" *-- "1..3" Vida
Mario "1" *-- "1" Puntaje
Mario "1" *-- "0..*" ProyectilFuego

KoopaTroopa "1" *-- "1" Caparazon

Mario *-- Crecimiento
Luigi *-- Crecimiento
Mario -- PrincesaPeach

Personaje "1" --> "0..*" Tuberia : usar

Mario "1" o-- "0..*" Hongo
Mario "1" o-- "0..*" FlorDeFuego
Mario "1" o-- "0..*" Estrella
Mario "1" o-- "0..*" Moneda

BloquePregunta "1" o-- "0..1" Hongo
BloquePregunta "1" o-- "0..1" FlorDeFuego
BloquePregunta "1" o-- "0..*" Moneda

Castillo "1" o-- "1" Bandera

@enduml