@startuml diagrama

class Juego
class Mundo
class Nivel
class Personaje
class Mario
class Luigi
class Enemigo
class Goomba
class KoopaTroopa
class Bowser
class JefeFinal
class Hongo
class FlorDeFuego
class Estrella
class Moneda
class Bloque
class BloquePregunta
class BloqueLadrillo
class Tuberia
class Vida
class Puntaje
class ProyectilFuego
class Caparazon

Mario --|> Personaje
Luigi --|> Personaje
Enemigo --|> Personaje
Goomba --|> Enemigo
KoopaTroopa --|> Enemigo
JefeFinal --|> Enemigo
Bowser --|> JefeFinal
BloquePregunta --|> Bloque
BloqueLadrillo --|> Bloque

Juego "1" *-- "1..*" Mundo
Mundo "1" *-- "1..*" Nivel
Nivel "1" *-- "1..*" Enemigo
Nivel "1" *-- "1..*" Bloque
Nivel "1" *-- "1..*" Plataforma
Nivel "1" *-- "0..*" Tuberia
Nivel "1" *-- "0..*" Moneda
Nivel "1" *-- "1" Bandera
Nivel "1" *-- "0..1" Castillo
Mario "1" *-- "1..∞" Vida
Mario "1" *-- "1" Puntaje
Mario "1" *-- "0..*" ProyectilFuego
KoopaTroopa "1" *-- "1" Caparazon
Mario*-- crecimiento
Luigi*-- crecimiento
Mario*-- PrincesaPeach

Mario "1" o-- "0..*" Hongo
Mario "1" o-- "0..*" FlorDeFuego
Mario "1" o-- "0..*" Estrella
Mario "1" o-- "0..*" Moneda

BloquePregunta "1" o-- "0..1" Hongo
BloquePregunta "1" o-- "0..1" FlorDeFuego
BloquePregunta "1" o-- "0..*" Moneda
Castillo "1" o-- "1" Bandera
@enduml